### ISSUE TITLE
faf-uid.exe trips antivirus

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/uid#10]
http://forums.faforever.com/viewtopic.php?f=3&t=13725

**Comment by muellni** [comment]
This doesn't look good: https://virustotal.com/en/file/beac27f43ccacf4e7cf03f239b77dcafac7682bf67325d8b9f80b4f043e66f97/analysis/
Maybe there's a compiler define I could try like the [security flag for network packets](https://www.ietf.org/rfc/rfc3514.txt).
But seriously: We're reading WMI and using RSA encryption. This seems to trigger AV somehow. Some options may be:
* do more obfuscating (but we're not a trojan)
* change compiler (I could try to build the whole exe on MSVC (on Appveyor) instead of MinGW (on Travis))
* search for some whilelisting options (but I'd expect the snake-oil industry to charge money for that)

**Comment by duk3luk3** [comment]
> search for some whilelisting options (but I'd expect the snake-oil industry to charge money for that)

No, most AV vendors let you submit/upload false positives for free. I've already done it for Bitdefender.

You should definitely check that you didn't set the evil bit somewhere :-)

**Comment by muellni** [comment]
It's down to 2 detections, I'll close this for now: https://virustotal.com/en/file/beac27f43ccacf4e7cf03f239b77dcafac7682bf67325d8b9f80b4f043e66f97/analysis/1482753670/
But we need to check each release I guess :(

**Comment by duk3luk3** [comment]
Oh good, that means my false positive notification must have worked :-)
